#!/bin/bash
# ask_google
# Gets lats and lons for places in the places file.  Sleeps a randomized
# time between calls to avoid robot blockage

while IFS="" read -r place || [ -n "$place" ]; do
    printf '%s|' "$place"
    # The particular string we search for in the result was found by manual inspection
    echo $(curl --get --data-urlencode "q=$place" "https://www.google.com/maps" --silent | sed -nr 's/.*\/@(-{0,1}[0-9\]+.[0-9]+),(-{0,1}[0-9]+.[0-9]+).*/\1|\2/p')
    sleep $((9 + $RANDOM % 100))
done < cache/broken_places
