#!/bin/bash
wget -O data/allCountries.zip \
        http://download.geonames.org/export/zip/allCountries.zip
zcat data/allCountries.zip > data/allCountries
wget -O data/allCountries.readme \
        http://download.geonames.org/export/dump/readme.txt
wget -O data/cities1000.zip \
        http://download.geonames.org/export/dump/cities1000.zip
zcat data/cities1000.zip > data/cities1000
wget -O data/cities1000.readme \
        http://download.geonames.org/export/dump/readme.txt
wget -O data/admin1CodesASCII.txt \
        http://download.geonames.org/export/dump/admin1CodesASCII.txt
wget -Odata/countryInfo.txt \
        http://download.geonames.org/export/dump/countryInfo.txt
