#!/bin/bash -f
#get_comps
api="https://www.thebluealliance.com/api/v3/events/"
auth="?X-TBA-Auth-Key=$(cat TBA-auth)"
wget -Odata/events-full "$api$(cat year)$auth"
(echo "// Data extracted from thebluealliance.com at $(TZ=utc date -Iseconds)" 
 echo "// Built by scraper at https://github/GeeII/Firstmap-scraper/"
 echo
 gawk -F: ' BEGIN       {regct=0; disct=0}
        /"abbreviation"/ {district=gensub("\"*, *$","",1,$2);  
                          gsub("^ *\"*","",district);}
        /"end_date"/     {end_date=gensub("\"*, *$","",1,$2);  
                          gsub("^ *\"*","",end_date);}
        /"start_date"/   {start_date=gensub("\"*, *$","",1,$2);
                          gsub("^ *\"*","",start_date);}
        /"event_type"/   {event_type=gensub("\"*, *$","",1,$2);
                          gsub("^ *\"*","",event_type);}
        /"name"/         {name=gensub("\"*, *$","",1,$2);      
                          gsub("^ *\"*","",name);}
        /"week"/         {week=gensub("\"*, *$","",1,$2);      
                          gsub("^ *\"*","",week);}
        /"key"/          {key=gensub("\"*, *$","",1,$2);       
                          gsub("^ *\"*","",key);}
        /"lat"/          {lat=gensub("\"*, *$","",1,$2);       
                          gsub("^ *\"*","",lat);}
        /"lng"/          {lng=gensub("\"*, *$","",1,$2);       
                          gsub("^ *\"*","",lng);}
        /^ }/ { 
                if (lat=="null" && key="2018chcmp") {lat=38.217;lng=-78.342;}
                entry=sprintf( \
                    "\"%s\", {lat:%.4f, lng:%.4f}, %d, \"%s\", \"%s - %s\"",
                    name, lat, lng, week, key, start_date, end_date);
                if (event_type == 0) {
                        regct++;
                        regionals[regct]=sprintf("[%s]",entry);
                } else if (event_type < 3) {
                        disct++;
                        districts[disct] =sprintf("[\"%s District\", %s]",
                              toupper(district),entry);
                }
            }
        END {
print "regct:",regct, "disct:", disct >> "/dev/stderr"
                printf "var regionals = [\n  " 
                for (i=1; i<regct; i++) {printf "%s,\n  ",regionals[i];}
                printf "%s\n]\n\n\nvar districts = [\n\n  ",regionals[regct];
                for (i=1; i<disct; i++) {printf "%s,\n  ",districts[i];}
                printf "%s\n]\n",districts[regct];
            }' data/events-full ) > competitions.js
