#!/bin/bash
# get_all_data
mkdir data
./get_postal     # get zip/postal code/city lookup info
./get_events     # get event data from theblualliance
./get_lists      # get team data from thebluealliance
./merge_lists    # merges team data from thebluealliance into one file
./build_quicktab # geocodes and builds team numbers, lat, lon
./qt2js

#-rwxr-xr-x  1 Daddy None    406 Oct  6 20:23 ask_google
