#!/bin/bash
#merge_lists
# merges the 50-team data files into a single file, and slims down the
# home_championship attribute to an atomic value.
year=$(cat YEAR)
year=2018
files=$(echo data/teams.? data/teams.??)
echo $files
awk -F'\0' 'BEGIN {start=1; wai=0}
	/[\[\]]/ {next}
	/^ *}/ {next}
	/^ *{/ {if (start) {start=0} else {print "  },"; }; }
	/home_championship/ {if (!/null/) wai=1; }
	/'$year'.:/ {sub("  .'$year'","\"home_championship"); sub("$",","); wai=0}
	{if ( wai == 1 ) {next}}
	{gsub("null","\"\"");}
	{print}
	END {printf "  }\n";}' $files > data/merged
