#!/bin/bash
# get_lists
api="https://www.thebluealliance.com/api/v3/teams/"
auth="?X-TBA-Auth-Key=$key$(cat TBA-auth)"
year=$(cat YEAR)
i=0;
go=1
while /bin/true
do	wget -O"data/teams.$i" "$api$year/$i$auth"
	go=$(grep -c -s key "data/teams.$i")
	if [ $go -ge 1 ] 
	then	echo "got data/teams.$i"
	else	echo "emty file for data/teams.$i; terminating"
		rm "data/teams.$i"
		exit 0
	fi
	i=$(expr $i + 1)
done
