#!/bin/bash -f
#htm2tab
tr '<>' '|' < data/cclist | \
   sed 's-|/*em|--g; s-|/*i|--g; s-|/*a[^|]*|--g;' | \
   sed 's-|[[:space:]]*-|-g; s-[[:space:]]*|-|-g;' | \
   gawk -F\| '
	BEGIN		{p=0}
	{gsub("&nbsp;","");
	 gsub("&eacute;","e");
	 gsub("&ocirc;","o");
	}
	($2~/\/table/)	{p=0}
	($2 ~ /^tr/)	{rec=0}
	($2 ~ /^td/)	{rec++}
			{if (p && rec>1 && rec<4) {
                              printf "%s%s", $3, (rec==2?"\t":"\n")}}
	/codelist/	{p=1}' > data/country-2digit 
